name: Check infra code

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: brpaz/hadolint-action@master
        name: hadolint
        with:
          dockerfile: docker/Dockerfile
      - name: validate-cfn
        run: |
          aws cloudformation validate-template --template-file file://aws/vpc.yaml
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-northeast-1
