name: Blank workflow

on: [push]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: brpaz/hadolint-action@master
      name: hadolint
      with:
        dockerfile: docker/Dockerfile
